### ISSUE TITLE
Successfull sign in but failure at download backup

### ISSUE THREAD

**Issue by meegoSVK** [mattwebbio/orbital-sync#176]
### What happened?

Hi.

I experience having problem with syncing two PiHoles.
One runs as Virtual Machine on ESXi virtualized host (CentOS 9) -> this one is supposed to be the primary one where all changes are done. It is default CentOS installation with fresh pihole installation.
The standby one runs in docker container (pihole dockerfile).

Both pihole run on http port 80 (without certificates).

Orbital sync is also run from container. I run it as a stack with this docker compose file:

```
version: '3'

networks:
  macvlan1:
    external: true
    name: macvlan1
  common_network:
    external: true
    name: common_network

volumes:
  pihole_config:
    external: true
  pihole_dnsmasq:
    external: true


services:
  orbital-sync:
    container_name: orbital_sync
    image: mattwebbio/orbital-sync:1
    depends_on:
      - pihole
    links:
      - pihole
    environment:
      - PRIMARY_HOST_BASE_URL
      - PRIMARY_HOST_PASSWORD
      - SECONDARY_HOST_1_BASE_URL
      - SECONDARY_HOST_1_PASSWORD
      - INTERVAL_MINUTES
      - VERBOSE
      - TZ
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    volumes:
      - pihole_config:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    networks:
      macvlan1:
        ipv4_address: ${SECONDARY_HOST_IPV4}
      common_network: {}
    environment:
      - TZ
      - WEBPASSWORD

```
I am able to manually log into the primary pihole from browser and download the file.

Whe I try to curl the the admin page I got 301 moved permanently -> this does not bother me so much, because I am able to interact with pihole via browser.

```
Meego@MEEGO-DESKTOP ~
$ curl -v netcontrol/admin
*   Trying 192.168.2.60:80...
* Connected to netcontrol (192.168.2.60) port 80 (#0)
> GET /admin HTTP/1.1
> Host: netcontrol
> User-Agent: curl/8.0.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Location: /admin/
< Content-Length: 0
< Date: Fri, 21 Apr 2023 23:48:52 GMT
< Server: lighttpd/1.4.67
<
* Connection #0 to host netcontrol left intact
```

I am confused with that Not Authorized response with response code 200 -> This might be problem on pihole side, because Not Authorized should return 401.

Thank you very much for your time and help.

Have a nice day.

### Version

latest docker file

### Log output

```shell
4/22/2023, 1:33:05 AM: Waiting 5 minutes...
4/22/2023, 1:38:05 AM: ➡️ Signing in to http://netcontrol.home.local/admin...
4/22/2023, 1:38:05 AM: ✔️ Successfully signed in to http://netcontrol.home.local/admin!
4/22/2023, 1:38:05 AM: ➡️ Downloading backup from http://netcontrol.home.local/admin...
4/22/2023, 1:38:05 AM: ⚠ Failure: Failed to download backup from "http://netcontrol.home.local/admin".
4/22/2023, 1:38:05 AM: {"host":"http://netcontrol.home.local","path":"/admin","status":200,"responseBody":"Not authorized"}
```

**Comment by barstown** [comment]
I'm seeing the exact same behavior currently. My Pi-hole instances are running on separate VM's, instead of docker, but my docker host running orbital-sync has access to both. I've tried with and without host networking as well just to be safe. Verbose logging is on, and shows exactly what @meegoSVK is seeing. Successful sign ins, following by a failure to download the backup with the same "Not Authorized" error and a status of 200.

```
version: "3.7"

services:
  orbital-sync:
    image: ghcr.io/mattwebbio/orbital-sync:latest
    container_name: orbital-sync
    environment:
      - PRIMARY_HOST_BASE_URL=http://xxx.xxx.xxx.101
      - PRIMARY_HOST_PATH=/admin
      - PRIMARY_HOST_PASSWORD=********
      - SECONDARY_HOST_1_BASE_URL=http://xxx.xxx.xxx.102
      - SECONDARY_HOST_1_PATH=/admin
      - SECONDARY_HOST_1_PASSWORD=********
      - INTERVAL_MINUTES=30
      - UPDATE_GRAVITY=true
      - TZ=America/New_York
      - VERBOSE=true
    restart: unless-stopped
```
```
4/23/2023, 10:35:59 PM: ➡️ Signing in to http://xxx.xxx.xxx.101/admin...
4/23/2023, 10:35:59 PM: ✔️ Successfully signed in to http://xxx.xxx.xxx.101/admin!
4/23/2023, 10:35:59 PM: ➡️ Downloading backup from http://xxx.xxx.xxx.101/admin...
4/23/2023, 10:35:59 PM: ⚠ Failure: Failed to download backup from "http://xxx.xxx.xxx.101/admin".
4/23/2023, 10:35:59 PM: {"host":"http://xxx.xxx.xxx.101","path":"/admin","status":200,"responseBody":"Not authorized"}
4/23/2023, 10:35:59 PM: Waiting 30 minutes...
```
