### ISSUE TITLE
new docker install 1.6 wont start

### ISSUE THREAD

**Issue by Raabi91** [mattwebbio/orbital-sync#275]
### What happened?

hello
i started orbital sync for the first time today and it won't start.

config as follows

```
  orbital-sync:
    container_name: orbital-sync
    image: mattwebbio/orbital-sync:latest
    environment:
      PRIMARY_HOST_BASE_URL: http://ip:180
      PRIMARY_HOST_PASSWORD: xxxxxxx
      PRIMARY_HOST_PATH: /admin
      SECONDARY_HOSTS_BASE_URL_1: http://ip:180
      SECONDARY_HOSTS_PASSWORD_1: xxxxxxx
      SECONDARY_HOSTS_PATH_1: /admin
      INTERVAL_MINUTES: 1440
      VERBOSE: true
```

### Version

1.6

### Log output

```shell
file:///usr/src/app/dist/config/parse.js:67

                throw new MissingRequiredPropertiesError(path, missingRequired);

                      ^

MissingRequiredPropertiesError: Missing required properties for "secondaryHosts.1": baseUrl, password

    at parseSchema (file:///usr/src/app/dist/config/parse.js:67:23)

    at parseSchema (file:///usr/src/app/dist/config/parse.js:36:32)

    at file:///usr/src/app/dist/config/parse.js:60:17

    at Array.map (<anonymous>)

    at parseSchema (file:///usr/src/app/dist/config/parse.js:57:62)

    at Config (file:///usr/src/app/dist/config/index.js:5:12)

    at file:///usr/src/app/dist/index.js:7:16

    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)

    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)

    at async loadESM (node:internal/process/esm_loader:34:7)

Node.js v18.19.1
```

**Comment by mattwebbio** [comment]
Hey @Raabi91! I'm so sorry about this - I refactored a big chunk of the code, and messed up the documentation. Could you try this instead? 

```
orbital-sync:
    container_name: orbital-sync
    image: mattwebbio/orbital-sync:latest
    environment:
      PRIMARY_HOST_BASE_URL: http://ip:180
      PRIMARY_HOST_PASSWORD: xxxxxxx
      PRIMARY_HOST_PATH: /admin
      SECONDARY_HOSTS_1_BASE_URL: http://ip:180
      SECONDARY_HOSTS_1_PASSWORD: xxxxxxx
      SECONDARY_HOSTS_1_PATH: /admin
      INTERVAL_MINUTES: 1440
      VERBOSE: true
```
