### ISSUE TITLE
Syncing with Pihole behind HTTPS Web Proxy using self signed cert

### ISSUE THREAD

**Issue by aloyweesious** [mattwebbio/orbital-sync#472]
### What feature would you like added?

Add the options to allow users to disable TLS verification or to set the ca cert to be used.

# Background
I am running pihole behind a web proxy (nginx proxy manager in my case) so that access to pihole admin is via https.

# Workaround
What I am doing now is to mount the self signed CA cert at ` /etc/ssl/certs/ca.crt` from host to the container.
Then set the env var `NODE_EXTRA_CA_CERTS` to the point to the mounted cert at `/etc/ssl/certs/ca.crt`

``` yaml
services:
  orbital-sync:
    image: mattwebbio/orbital-sync:1
    environment:
      ...
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca.crt
    extra_hosts:
      - "pihole2.homelab=192.168.1.53"
    volumes:
      - /etc/ssl/certs/ca.crt:/etc/ssl/certs/ca.crt:ro
...
```

### Version

1

### Log output

```shell
11/23/2024, 9:42:53 AM: ➡️ Signing in to https://pihole2.homelab/admin...
11/23/2024, 9:42:53 AM: ⚠ Failure: An unexpected error was thrown:
- FetchError: request to https://pihole2.homelab/admin/index.php?login failed, reason: unable to verify the first certificate
11/23/2024, 9:42:53 AM: ⚠ Failure: 0/1 hosts synced.
```
