### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by Zohnda** [mattwebbio/orbital-sync#539]
### What happened?

**ISSUE**

Used the docker compose file from the example, logging into the web interface works as expected. First PiHole instance is on a proxmox LXC container, debian 12. Second is a pi 4 running ubuntu 22.04. Both work as expected as DNS servers. Every time I bring the docker container up (which is running on the first PiHole machine, I get login failures. I tried switching the second machine as the PRIMARY_HOST and the first machine as the SECONDARY_HOST with the same results. I've confirmed passwords in the docker-compose.yml file are good. I noticed when bringing up the container, the time in the logs was way off so I added the TZ line, which didn't change anything.

```
version: '3'
services:
  orbital-sync:
    image: mattwebbio/orbital-sync:1
    environment:
      PRIMARY_HOST_BASE_URL: 'http://192.168.0.104'
      PRIMARY_HOST_PASSWORD: 'somethingSecret'
      SECONDARY_HOSTS_1_BASE_URL: 'http://192.168.0.220'
      SECONDARY_HOSTS_1_PASSWORD: 'somethingSecret'
      INTERVAL_MINUTES: 60
      TZ: "America/Los_Angeles"
```

### Version

latest

### Log output

```
[+] Running 9/9
 ✔ orbital-sync Pulled                                                                                                                                5.4s 
   ✔ 1f3e46996e29 Pull complete                                                                                                                       0.7s 
   ✔ 4e8e5b9bf1c9 Pull complete                                                                                                                       2.5s 
   ✔ 56147f690fe6 Pull complete                                                                                                                       2.6s 
   ✔ be1495f7193c Pull complete                                                                                                                       2.6s 
   ✔ ffbe97c2485f Pull complete                                                                                                                       2.7s 
   ✔ c6dc951239f7 Pull complete                                                                                                                       2.7s 
   ✔ 82ff2f6c986d Pull complete                                                                                                                       2.8s 
   ✔ d8d9c59b6fee Pull complete                                                                                                                       3.8s 
[+] Running 1/1
 ✔ Container orbitalsync-orbital-sync-1  Created                                                                                                      0.3s 
Attaching to orbital-sync-1
orbital-sync-1  | 2/26/2025, 10:38:43 AM: ➡️ Signing in to http://192.168.0.220:80/admin...
orbital-sync-1  | 2/26/2025, 10:38:43 AM: ⚠ Failure: There was an error logging in to "http://192.168.0.220:80/admin" - are you able to log in with the configured password?
orbital-sync-1  | 2/26/2025, 10:38:43 AM: Waiting 60 minutes...
```
