### ISSUE TITLE
There was an error logging in

### ISSUE THREAD

**Issue by r0mantik4** [mattwebbio/orbital-sync#540]
### What happened?

I'm trying to set up Orbital-Sync using Docker, but authentication fails with the error:
⚠ Failure: There was an error logging in to "http://192.168.1.3/admin" - are you able to log in with the configured password?

docker-compose.yml
```
services:
  orbital-sync:
    container_name: orbital-sync
    image: mattwebbio/orbital-sync:1
    restart: unless-stopped
    environment:
      PRIMARY_HOST_BASE_URL: "http://192.168.1.3"
      PRIMARY_HOST_PASSWORD: "pwd11"
      SECONDARY_HOSTS_1_BASE_URL: "http://192.168.1.10"
      SECONDARY_HOSTS_1_PASSWORD: "pwd11"
      SECONDARY_HOSTS_2_BASE_URL: "http://192.168.1.11"
      SECONDARY_HOSTS_2_PASSWORD: "pwd11"
      INTERVAL_MINUTES: 5  # Sync interval
    networks:
      - pihole_network

networks:
  pihole_network:
    driver: bridge
```
What I have tried:
Manually logging in – I can successfully log in to http://192.168.1.3/admin via the browser with the same credentials.
Testing with cURL:
curl -v -X POST http://192.168.1.3/admin -d "password=pwd11"
The response is:
HTTP/1.1 302 Found
Location: /admin/login

This suggests that authentication might require a different endpoint.

Tried changing PRIMARY_HOST_BASE_URL to http://192.168.1.3/admin/, but the issue persists.
Checked environment variables inside the container using:

docker exec -it orbital-sync env | grep PASSWORD
The variables are correctly set.

### Version

latest

### Log output

```shell
2/27/2025, 7:44:39 AM: ➡️ Signing in to http://192.168.1.3/admin...
2/27/2025, 7:44:39 AM: ⚠ Failure: There was an error logging in to "http://192.168.1.36/admin" - are you able to log in with the configured password?
2/27/2025, 7:44:39 AM: Waiting 5 minutes...
```
