### ISSUE TITLE
(V6) Sync takes my 2 secondary piholes offline for 2-5 minutes

### ISSUE THREAD

**Issue by feerlessleadr** [mattwebbio/orbital-sync#564]
### What happened?

I am using the latest version (as of 6:35pm ET from [ghcr.io/mattwebbio/orbital-sync:master](here).

I do something a little unique in that I have 3 pihole instances running. They are as follows:

1. pivpn w/ pihole running on an ubuntu VM in my main proxmox node
2. pihole CT running on a second proxmox node
3. pihole CT running on a third proxmox node

My pivpn instance is only used by my phones/devices that I use on the go and leave connected to that VPN all the time. The other devices on my network are not served that IP as a DNS from my opnsense router

My 2 other piholes serve as my main pihole instaces for my network, and are given as dns servers by my opnsense dhcp server. 

The issue I'm running into is that when orbital sync runs, it takes down both of my secondary piholes for between 2-5 minutes. I'm still able to ssh into the CT containers, and run commands, but the pihole interface will not load. After a while of waiting, it seems the pihole interfaces come back up, but like I said, obviously my network being down for 2-5 minutes every hour is not what is supposed to happen. 

Here is my compose file for orbital sync. Please note that I am using the full config sync because I have local dns entires that I need synced, but I tried both with that variable set to both true and false, and had the same issue. 

```
version: "3"
services:
  orbital-sync:
    image: ghcr.io/mattwebbio/orbital-sync:master
    environment:
      PRIMARY_HOST_BASE_URL: http://192.168.1.5
      PRIMARY_HOST_PASSWORD: ""
      SECONDARY_HOSTS_1_BASE_URL: http://192.168.1.3
      SECONDARY_HOSTS_1_PASSWORD: ""
      SECONDARY_HOSTS_2_BASE_URL: http://192.168.1.4
      SECONDARY_HOSTS_2_PASSWORD: ""
      SYNC_V6_CONFIG: true
      NOTIFY_ON_SUCCESS: true
      NOTIFY_SMTP_ENABLED: true
      NOTIFY_SMTP_FROM: orbitalsync@mydomain.com
      NOTIFY_SMTP_TO: myemail@mydomain.com
      NOTIFY_SMTP_HOST: smtp.myemailprovider.com
      NOTIFY_SMTP_PORT: 587
      NOTIFY_SMTP_USER: myemail@mydomain.com
      NOTIFY_SMTP_PASSWORD: mysupersecretpassword
    restart: unless-stopped
networks: {}
```

Not much from the logs, but here is the docker log from dockge when I ran the container. The failure for updating gravity on one of my pihole containers was because I took it offline to restore from a backup on my proxmox server, since it didn't look like it was coming back up, and my kids were yelling at me that youtube wasn't working.  See below for logs. 

### Version

not sure, latest version from here: ghcr.io/mattwebbio/orbital-sync:master

### Log output

```shell
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: Checking PiHole version for http://192.168.1.5...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ✔️ PiHole (v6) API is available for http://192.168.1.5
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ➡️ Signing in to http://192.168.1.5...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ✔️ Successfully signed in to http://192.168.1.5!
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ➡️ Downloading backup from http://192.168.1.5...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ✔️ Backup from http://192.168.1.5 completed!
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: Checking PiHole version for http://192.168.1.3:8080...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: Checking PiHole version for http://192.168.1.4...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ✔️ PiHole (v6) API is available for http://192.168.1.3:8080
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ➡️ Signing in to http://192.168.1.3:8080...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ✔️ PiHole (v6) API is available for http://192.168.1.4
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ➡️ Signing in to http://192.168.1.4...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ✔️ Successfully signed in to http://192.168.1.3:8080!
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ➡️ Uploading backup to http://192.168.1.3:8080...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ✔️ Successfully signed in to http://192.168.1.4!
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ➡️ Uploading backup to http://192.168.1.4...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ✔️ Backup uploaded to http://192.168.1.3:8080!
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:03 PM: ➡️ Attempting to update gravity on http://192.168.1.3:8080...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:04 PM: ✔️ Backup uploaded to http://192.168.1.4!
orbital-sync-orbital-sync-1  | 3/11/2025, 10:30:04 PM: ➡️ Attempting to update gravity on http://192.168.1.4...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:37 PM: Sleeping for 1s and waiting for http://192.168.1.3:8080 to be up...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:38 PM: ➡️ Attempting to update gravity on http://192.168.1.3:8080...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:38 PM: Sleeping for 2s and waiting for http://192.168.1.3:8080 to be up...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:40 PM: ➡️ Attempting to update gravity on http://192.168.1.3:8080...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:40 PM: Sleeping for 4s and waiting for http://192.168.1.3:8080 to be up...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:44 PM: ➡️ Attempting to update gravity on http://192.168.1.3:8080...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:44 PM: Sleeping for 8s and waiting for http://192.168.1.3:8080 to be up...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:45 PM: Sleeping for 1s and waiting for http://192.168.1.4 to be up...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:46 PM: ➡️ Attempting to update gravity on http://192.168.1.4...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:46 PM: Sleeping for 2s and waiting for http://192.168.1.4 to be up...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:48 PM: ➡️ Attempting to update gravity on http://192.168.1.4...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:48 PM: Sleeping for 4s and waiting for http://192.168.1.4 to be up...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:52 PM: ➡️ Attempting to update gravity on http://192.168.1.4...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:35:52 PM: ➡️ Attempting to update gravity on http://192.168.1.3:8080...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:36:03 PM: Sleeping for 16s and waiting for http://192.168.1.3:8080 to be up...
orbital-sync-orbital-sync-1  | 3/11/2025, 10:36:19 PM: ⚠ Error: Exhausted 6 retries updating gravity on http://192.168.1.3:8080.
orbital-sync-orbital-sync-1  | 3/11/2025, 10:37:15 PM: ✔️ Gravity updated on http://192.168.1.4!
orbital-sync-orbital-sync-1  | 3/11/2025, 10:37:15 PM: ⚠ Failure: 1/2 hosts synced.
orbital-sync-orbital-sync-1  | 3/11/2025, 10:37:16 PM: Waiting 60 minutes...
```
